### ISSUE TITLE
Payment impossible due to header overflow error

### ISSUE THREAD

**Issue by TobyJA** [woocommerce/woocommerce-paypal-payments#1620]
Hello,

we installed and set up the plugin and the connection to PayPal Pro is also working. But it is not possible to buy something via PayPal. Paying with credit card with another plugin is possible.

What is going on?
After clicking on the PayPal button on the checkout page, the window to signing in the personal PayPal account opens. Enter email and password also working fine. But this is it.

The window gets white with just the error message "Header overflow"

We tried it many times with different browsers, but always the same result.

What wonders me, is the massive URL. It is very long and includes also empty spaces.

This the Original URL:
[paypal.com/signin?intent=checkout&ctxId=xo_ctx_2FP424325G542984M&returnUri=%2Fwebapps%2Fhermes&state=%3Fflow%3D1-P%26ulReturn%3Dtrue%26sessionID%3Duid_a22719861e_mtq6mdm6mza%26buttonSessionID%3Duid_fa7daca4f6_mtq6mdm6mzi%26stickinessID%3Duid_dec5e0287f_mtq6mdm6mza%26smokeHash%3D%26token%3D2FP424325G542984M%26fundingSource%3Dpaypal%26buyerCountry%3DDE%26locale.x%3Dde_DE%26commit%3Dtrue%26enableFunding.0%3Dvenmo%26clientID%3DAYvpTzn34y4fpz28uaNk4_mIo2vVnSnJQwfOqmMHObP_7OMBKHMCi5iKNCIE28LfDfJVAbtT_BuyFahI%26env%3Dproduction%26sdkMeta%3DeyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVl2cFR6bjM0eTRmcHoyOHVhTms0X21JbzJ2Vm5TbkpRd2ZPcW1NSE9iUF83T01CS0hNQ2k1aUtOQ0lFMjhMZkRmSlZBYnRUX0J1eUZhaEkmY3VycmVuY3k9RVVSJmludGVncmF0aW9uLWRhdGU9MjAyMy0wNy0wNiZjb21wb25lbnRzPWJ1dHRvbnMsZnVuZGluZy1lbGlnaWJpbGl0eSxtZXNzYWdlcyZ2YXVsdD1mYWxzZSZjb21taXQ9dHJ1ZSZpbnRlbnQ9Y2FwdHVyZSZkaXNhYmxlLWZ1bmRpbmc9Y2FyZCxzZXBhLGdpcm9wYXksc29mb3J0LHBheWxhdGVyJmVuYWJsZS1mdW5kaW5nPXZlbm1vIiwiYXR0cnMiOnsiZGF0YS1wYXJ0bmVyLWF0dHJpYnV0aW9uLWlkIjoiV29vX1BQQ1AiLCJkYXRhLXVpZCI6InVpZF95dW1lc3Vtb295bWhoenhjZXFhdGhmZG9zd2tkdGMifX0%26xcomponent%3D1%26version%3D5.0.394%26ssrt%3D1692885822186%26rcache%3D1%26useraction%3DPAY%26cookieBannerVariant%3Dhidden&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVl2cFR6bjM0eTRmcHoyOHVhTms0X21JbzJ2Vm5TbkpRd2ZPcW1NSE9iUF83T01CS0hNQ2k1aUtOQ0lFMjhMZkRmSlZBYnRUX0J1eUZhaEkmY3VycmVuY3k9RVVSJmludGVncmF0aW9uLWRhdGU9MjAyMy0wNy0wNiZjb21wb25lbnRzPWJ1dHRvbnMsZnVuZGluZy1lbGlnaWJpbGl0eSxtZXNzYWdlcyZ2YXVsdD1mYWxzZSZjb21taXQ9dHJ1ZSZpbnRlbnQ9Y2FwdHVyZSZkaXNhYmxlLWZ1bmRpbmc9Y2FyZCxzZXBhLGdpcm9wYXksc29mb3J0LHBheWxhdGVyJmVuYWJsZS1mdW5kaW5nPXZlbm1vIiwiYXR0cnMiOnsiZGF0YS1wYXJ0bmVyLWF0dHJpYnV0aW9uLWlkIjoiV29vX1BQQ1AiLCJkYXRhLXVpZCI6InVpZF95dW1lc3Vtb295bWhoenhjZXFhdGhmZG9zd2tkdGMifX0&locale.x=de_DE&country.x=DE&flowId=2FP424325G542984M](https://www.paypal.com/signin?intent=checkout&ctxId=xo_ctx_2FP424325G542984M&returnUri=%2Fwebapps%2Fhermes&state=%3Fflow%3D1P%26ulReturn%3Dtrue%26sessionID%3Duid_a22719861e_mtq6mdm6mza%26buttonSessionID%3Duid_fa7daca4f6_mtq6mdm6mzi%26stickinessID%3Duid_dec5e0287f_mtq6mdm6mza%26smokeHash%3D%26token%3D2FP424325G542984M%26fundingSource%3Dpaypal%26buyerCountry%3DDE%26locale.x%3Dde_DE%26commit%3Dtrue%26enableFunding.0%3Dvenmo%26clientID%3DAYvpTzn34y4fpz28uaNk4_mIo2vVnSnJQwfOqmMHObP_7OMBKHMCi5iKNCIE28LfDfJVAbtT_BuyFahI%26env%3Dproduction%26sdkMeta%3DeyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVl2cFR6bjM0eTRmcHoyOHVhTms0X21JbzJ2Vm5TbkpRd2ZPcW1NSE9iUF83T01CS0hNQ2k1aUtOQ0lFMjhMZkRmSlZBYnRUX0J1eUZhaEkmY3VycmVuY3k9RVVSJmludGVncmF0aW9uLWRhdGU9MjAyMy0wNy0wNiZjb21wb25lbnRzPWJ1dHRvbnMsZnVuZGluZy1lbGlnaWJpbGl0eSxtZXNzYWdlcyZ2YXVsdD1mYWxzZSZjb21taXQ9dHJ1ZSZpbnRlbnQ9Y2FwdHVyZSZkaXNhYmxlLWZ1bmRpbmc9Y2FyZCxzZXBhLGdpcm9wYXksc29mb3J0LHBheWxhdGVyJmVuYWJsZS1mdW5kaW5nPXZlbm1vIiwiYXR0cnMiOnsiZGF0YS1wYXJ0bmVyLWF0dHJpYnV0aW9uLWlkIjoiV29vX1BQQ1AiLCJkYXRhLXVpZCI6InVpZF95dW1lc3Vtb295bWhoenhjZXFhdGhmZG9zd2tkdGMifX0%26xcomponent%3D1%26version%3D5.0.394%26ssrt%3D1692885822186%26rcache%3D1%26useraction%3DPAY%26cookieBannerVariant%3Dhidden&sdkMeta=eyJ1cmwiOiJodHRwczovL3d3dy5wYXlwYWwuY29tL3Nkay9qcz9jbGllbnQtaWQ9QVl2cFR6bjM0eTRmcHoyOHVhTms0X21JbzJ2Vm5TbkpRd2ZPcW1NSE9iUF83T01CS0hNQ2k1aUtOQ0lFMjhMZkRmSlZBYnRUX0J1eUZhaEkmY3VycmVuY3k9RVVSJmludGVncmF0aW9uLWRhdGU9MjAyMy0wNy0wNiZjb21wb25lbnRzPWJ1dHRvbnMsZnVuZGluZy1lbGlnaWJpbGl0eSxtZXNzYWdlcyZ2YXVsdD1mYWxzZSZjb21taXQ9dHJ1ZSZpbnRlbnQ9Y2FwdHVyZSZkaXNhYmxlLWZ1bmRpbmc9Y2FyZCxzZXBhLGdpcm9wYXksc29mb3J0LHBheWxhdGVyJmVuYWJsZS1mdW5kaW5nPXZlbm1vIiwiYXR0cnMiOnsiZGF0YS1wYXJ0bmVyLWF0dHJpYnV0aW9uLWlkIjoiV29vX1BQQ1AiLCJkYXRhLXVpZCI6InVpZF95dW1lc3Vtb295bWhoenhjZXFhdGhmZG9zd2tkdGMifX0&locale.x=de_DE&country.x=DE&flowId=2FP424325G542984M)

Our System:

 - WordPress Version: 6.3
 - WooCommerce Version: 8.0.2
 - Plugin Version: 2.2.0
 - Browser Version: Current versions of Firefox, Chrome and Edge were used
 - Any other plugins installed: WooCommere Payments (Version 6.3.2), germanized for woocommerce, WP-Optimize
 - Theme: woodmart theme

Looking for help.
Thanks everyone who knows a solution.

Greeting
Toby

**Comment by InpsydeNiklas** [comment]
Hi @TobyJA 
This "Header Overflow" message typically is a local problem on your end device and can typically be resolved by clearing your PayPal-related browser cookies. There is also currently an [ongoing service disruption at PayPal](https://www.paypal-status.com/incident/production).
That being said, it seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

We'll close this GitHub issue for now. However, our support team is ready to assist you with your concerns. Thank you for your understanding!

**Comment by TobyJA** [comment]
Hello,

thanks for the information. Even when all cookies are deleted, the payment process is still not working. 
For me, it is okay, to close it.

This means: The problem is on the development schedule and there will be a solution in near future?

**Comment by Tjrvn** [comment]
Hi

I'd like to weigh in here.
We have exactly the same problem since today. The process works fine for many shoppers. So far, three buyers have contacted me describing this problem today.

I am not sure, but possibly it can also be related to Woodmart. There in the forum, another user has already described this problem:
https://xtemos.com/forums/topic/big-trouble-with-payment/

Maybe you can still take a look at it. Deleting the browser data did not help either.

**Comment by TobyJA** [comment]
Hello Tjrvn,

thanks for your comment. It is sad, that you also have the same problem. Especially because your customers already facing the problem :(
On Tuesday, we did PayPal Payments successfully. But since yesterday, PayPal is down in our shop. I hope this will be fixed very quick, or we have to delete the PayPal payment option.

**Comment by SoftwareSchlosser** [comment]
Same here

**Comment by Irfan-Jamal** [comment]
same issue

**Comment by Droidchris79** [comment]
Same here

**Comment by Tjrvn** [comment]
> I am not sure, but possibly it can also be related to Woodmart. There in the forum, another user has already described this problem: https://xtemos.com/forums/topic/big-trouble-with-payment/

I found out that it's not the theme. The problem exists even with a default theme enabled.

**Comment by Irfan-Jamal** [comment]
yes

**Comment by Droidchris79** [comment]
Works again for me. Must have been an PP issue. Would be nice to hear if this was the case, so I can close my internal error case.

**Comment by Tjrvn** [comment]
> Works again for me. Must have been an PP issue. Would be nice to hear if this was the case, so I can close my internal error case.

On my site its not. Also with cleared browser data.

**Comment by Droidchris79** [comment]
Stopped working again.

**Comment by TobyJA** [comment]
Thanks for the information. It worked for a short period. I don't know why, because we didn't change anything. But now again the error message "header overflow". Need a solution, please. Customers are forced to use some other payment method.

**Comment by Droidchris79** [comment]
Im running two websites. On one I created a new app. The other wasn't changed. Both worked for a short time. So it must be an transaction / configuration issue at pp.

**Comment by InpsydeNiklas** [comment]
There was a [service disruption at PayPal](https://www.paypal-status.com/history/eventdetails/69728) that impacted multiple products, including customer login functionality. By now, most systems should be stable again, so if you continue to encounter any issues with the payment process due to inability to log in, we recommend contacting the [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport).

For any questions relating directly to the PayPal Payments plugin, please contact our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). Thank you!

**Comment by Petbeginners** [comment]
Hello, we are experiencing the same issue across all our websites. Customers are getting this "header overflow" error when signing in to PayPal using PayPal express. Is this an issue with PayPal or with the plugin? Deleting cookies, clearing cache did not resolve the issue. @InpsydeNiklas

**Comment by Droidchris79** [comment]
> Hello, we are experiencing the same issue across all our websites. Customers are getting this "header overflow" error when signing in to PayPal using PayPal express. Is this an issue with PayPal or with the plugin? @InpsydeNiklas

It's an paypal issue, see https://github.com/woocommerce/woocommerce-paypal-payments/issues/1620#issuecomment-1693580102

**Comment by Petbeginners** [comment]
@Droidchris79 PayPal is not reporting any errors on the 25th but we are still getting this issue. See https://www.paypal-status.com/history/production

**Comment by CarlMahnke1** [comment]
Same here.

**Comment by Droidchris79** [comment]
Contacted PP support - they say it's a customer issue :/
Customers who can't login shell contact PP support.
To all with the same issue:
Do you geht this 403 message in PayPal Developer Dashbord, too?
      {
        "message": "This merchant account is not permitted to create Merchant Initiated Billing Agreement",
        "name": "REFUSED_MARK_REF_TXN_NOT_ENABLED"
      }

**Comment by TobyJA** [comment]
It worked today for about an hour. We did two payments for testing. Worked great But now "header overflow" error again.
Thanks Droidchris for the information. We contact them now. Day 4 of this problem. Customer writing mails and we always write the same answers. Frustrating.

**Comment by TobyJA** [comment]
@Droidchris79 
Yes. We also have the same error 403 message in our developer dashboard.

**Comment by slawkens** [comment]
Same problem here. I am a customer 😃

**Comment by Irfan-Jamal** [comment]
Since I used an alternative plugin called "Payment plugin for PayPal wooCommerce" It does not show any issue.
I am sure this is a bug in the plugin that sends the wrong request to PPl, BTW this is the issue in the latest release update.
Can anyone test using a bit older version?

**Comment by Droidchris79** [comment]
Downgraded down to 2.1. - same issue

**Comment by TobyJA** [comment]
We use this Plugin and it's not working. 
https://wordpress.org/plugins/woocommerce-paypal-payments/

Which one are you using?

**Comment by Irfan-Jamal** [comment]
I am using this
https://wordpress.org/plugins/pymntpl-paypal-woocommerce/
it is working like a sharp

**Comment by Droidchris79** [comment]
Same here: changed plugin, works fine.

**Comment by Droidchris79** [comment]
This is really, really anoying. I don't know how many times the "original woocommerce paypal plugin" has been broken.
It seems to be a problem with "Vault Save your customer’s payment methods to speed up checkout." Gateway. By creating a new app in PP Dev and hooking it manual to WC PP-Payments, I could do one transaction. Than it broke again.
This app is really, really bad. Will switch to an other permanently.

**Comment by Tjrvn** [comment]
> Since I used an alternative plugin called "Payment plugin for PayPal wooCommerce" It does not show any issue. I am sure this is a bug in the plugin that sends the wrong request to PPl, BTW this is the issue in the latest release update. Can anyone test using a bit older version?

Using the alternative plugin works for me. Thank you.

Seems the Plugin is broken. Please have a look on it @InpsydeNiklas

**Comment by Irfan-Jamal** [comment]
BTW I have experienced that the alternative not official plugin bit more features than official

**Comment by TobyJA** [comment]
Thanks @Irfan-Jamal for the link. We now deleted the WooCommerce PayPal Payment Plugin and installed the alternative plugin. We did 4 four tests in 3 different browsers. 4 times success. We will do some more tests in the next hours to be sure before enabling PayPal again. At the moment, we can recommend this plugin.

**Comment by Irfan-Jamal** [comment]
@TobyJA My Pleasure

**Comment by XdekHckr** [comment]
my clients still have issue with it, clearing cookies helps

**Comment by XdekHckr** [comment]
> Since I used an alternative plugin called "Payment plugin for PayPal wooCommerce" It does not show any issue.
I am sure this is a bug in the plugin that sends the wrong request to PPl, BTW this is the issue in the latest release update.
Can anyone test using a bit older version?

I am having cache issue with plugin from "Payment Plugins for PayPal WooCommerce", so it's likely paypal issue, not plugin itself...

**Comment by TobyJA** [comment]
We now use "Payment Plugins for PayPal WooCommerce" like @XdekHckr for 3 days now and did several tests. Everything works and no "header overflow" error message.

**Comment by Irfan-Jamal** [comment]
@XdekHckr What do you mean by cache issue?

**Comment by Sirvijver** [comment]
Hello,

PayPal informed us 7 hours ago that they rolled out a potential fix for the Header Overflow issue. Could you please let us know if you see the issue fixed, or if you are still encountering this issue?

Thank you.

Kind regards,
Joost

**Comment by XdekHckr** [comment]
> @XdekHckr What do you mean by cache issue?

"This "Header Overflow" message typically is a local problem on your end device and can typically be resolved by clearing your PayPal-related browser cookies"
Clearing cookie by customers helps

> Hello,
> 
> PayPal informed us 7 hours ago that they rolled out a potential fix for the Header Overflow issue. Could you please let us know if you see the issue fixed, or if you are still encountering this issue?
> 
> Thank you.
> 
> Kind regards, Joost

As for now customers are reporting this issue, so maybe you are right and it's fixed. I will monitor it and keep on eye.
Thanks in advance.

**Comment by Droidchris79** [comment]
> Hello,
> 
> PayPal informed us 7 hours ago that they rolled out a potential fix for the Header Overflow issue. Could you please let us know if you see the issue fixed, or if you are still encountering this issue?
> 
> Thank you.
> 
> Kind regards, Joost

Hi Joost,

Plugin Version 2.2.2 fixed all mentioned issues.

**Comment by Sirvijver** [comment]
Hello @Droidchris79 

No, this update had nothing to do with the fix of this issue. This issue was completely resolved by PayPal on the server side. No changes were made in the plugin to get this resolved.

Kind regards, 
Joost

**Comment by kenelli** [comment]
Hi Guys,

Just wanted to let you know that this issue is still here in 2024, with the latest version of Woocommerce and the plugin (2.9.3). I've lost severals sales because of this sh**tty problem from Paypal

**Comment by XdekHckr** [comment]
> Hi Guys,
> 
> Just wanted to let you know that this issue is still here in 2024, with the latest version of Woocommerce and the plugin (2.9.3). I've lost severals sales because of this sh**tty problem from Paypal

Lmao, not surprised. PayPal is shitty payment processor anyway
