### ISSUE TITLE
SiteGround Optimizer incompatibility/bug

### ISSUE THREAD

**Issue by alekseyn1** [woocommerce/woocommerce-paypal-payments#651]
Hello,

We are hosted by siteground.com and use their Caching and Optimization plugin - SiteGround Optimizer

Also installed and configured WooCommerce PayPal Payments (set to auto-update) on the latest version as of today.

The following error shows up when configuring caching in the 'Frontend Optimization' section of 'SG Optimizer'

COULD NOT CONNECT TO THE WORDPRESS REST API
Either a security plugin, custom function, or rules in your .htaccess file is preventing the WordPress REST API from working properly. SiteGround Optimizer is using it to store its options and other functionalities so please make sure it works properly.

When the WooCommerce PayPal Payments plugin is deactivated - SG Optimizer settings work correctly and no error is displayed.

Talked to SiteGround tech support and they could not identify anything on their end.
This will impact all users hosted by Site Ground that have this plugin installed as part of their WooCommerce shop.

### Environment

 - WordPress Version - 5.9.3
 - WooCommerce Version -  6.5.1 
 - Plugin Version - 1.8.0
 - any browser
 - SiteGround Optimizer Version 7.1.1 

### Screenshot

https://snipboard.io/fapcLV.jpg

**Comment by InpsydeNiklas** [comment]
A potential compatibility issue with the SG Optimizer plugin has been addressed for the next update.
I'm not sure this is related to the same  thing, so could you give it a try with this pre-release version?: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/1.8.1-test1
Thanks!

**Comment by InpsydeNiklas** [comment]
Compatibility with the SiteGround Optimizer plugin was improved in https://github.com/woocommerce/woocommerce-paypal-payments/issues/797 following update 1.9.3.

**Comment by avviano** [comment]
I have 1.9.5 installed, and still have issues. I posted to WP support as well. In my case SG Optimizer works, but not the Paypal Payments plugin.

**Comment by ITCOACH-find-terapeut** [comment]
I have the same! 
.htaccess is deleted, but still

![Image](https://github.com/user-attachments/assets/ee456ede-45b6-451d-ac5e-a7fe68778638)

Speed Optimizer
 provided by SiteGround
Version 7.7.0
